apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend-deployment
  labels:
    app: backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
        - name: backend
          image: tenebris2/qairline-repo:backend
          ports:
            - containerPort: 8000
          env:
            - name: DATABASE_URL
              valueFrom:
                secretKeyRef:
                  name: my-app-secrets
                  key: DATABASE_URL
            - name: MAIL_USERNAME
              valueFrom:
                secretKeyRef:
                  name: my-app-secrets
                  key: MAIL_USERNAME
            - name: MAIL_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: my-app-secrets
                  key: MAIL_PASSWORD
            - name: MAIL_SERVER
              valueFrom:
                secretKeyRef:
                  name: my-app-secrets
                  key: MAIL_SERVER
            - name: SECRET_KEY
              valueFrom:
                secretKeyRef:
                  name: my-app-secrets
                  key: SECRET_KEY
---
apiVersion: v1
kind: Service
metadata:
  name: backend-service
spec:
  selector:
    app: backend
  ports:
    - name: backend-service-port
      protocol: TCP
      port: 8000
      targetPort: 8000
