---
- name: Install Pod Network
  hosts: master
  tasks:
    - name: Install Pod network
      shell: kubectl apply -f https://raw.githubusercontent.com/flannel-io/flannel/v0.26.3/Documentation/kube-flannel.yml
      args:
        chdir: /home/ubuntu
        creates: pod_network_setup.log
