- name: install Kubectl
  apt:
    name: kubectl=1.29.*
    state: present
- name: create an empty file for Kubeadm configuring
  copy:
    content: ""
    dest: /etc/kubernetes/kubeadm-config.yaml
    force: no
#
- name: initialize the cluster (this could take some time)
  shell: kubeadm init --ignore-preflight-errors=NumCPU,Mem --pod-network-cidr=10.244.0.0/16
  args:
    creates: /etc/kubernetes/manifests/kube-apiserver.yaml
- name: Create .kube directory
  file:
    path: "/home/ubuntu/.kube"
    state: directory
    mode: "0755"

- name: copy admin.conf to user's kube config
  copy:
    src: /etc/kubernetes/admin.conf
    dest: /home/ubuntu/.kube/config
    remote_src: yes
    owner: ubuntu
