name: Gitleaks Secrets Scan

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
jobs:
  secrets-scan:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Run Gitleaks
        uses: gitleaks/gitleaks-action@v2
        with:
          config-path: .github/gitleaks.toml  # optional custom config
